# Add 'DB3K' label if DB Selector is set to 'DB3K' or "Both".
DB3K:
  - '### DB Selector\n+(DB3K|Both)'

# Add 'CWDB' label if DB Selector is set to 'CWDB' or "Both".
CWDB:
  - '### DB Selector\n+(CWDB|Both)'

# Add 'hypo' label if Hypothetical selector is set to 'Yes'.
hypo:
  - '### Hypothetical\n+Yes'

# Add respective annex labels to update/copy requests if Affected DBID / DBID to Copy field begins with key letters.
aircraft:
  - '### (?:Affected DBID\(s\)|DBID to Copy)\n+(?:(?:[Cc][Ww])?[Dd][Bb](?:3[Kk])?)? *[Aa](?:ir\w*|\/?[Cc]) *#?\d{0,4}'

facility:
  - '### (?:Affected DBID\(s\)|DBID to Copy)\n+(?:(?:[Cc][Ww])?[Dd][Bb](?:3[Kk])?)? *[Ff]a\w* *#?\d{0,4}'

ship:
  - '### (?:Affected DBID\(s\)|DBID to Copy)\n+(?:(?:[Cc][Ww])?[Dd][Bb](?:3[Kk])?)? *[Ss]hip|[Bb]oat *#?\d{0,4}'

submarine:
  - '### (?:Affected DBID\(s\)|DBID to Copy)\n+(?:(?:[Cc][Ww])?[Dd][Bb](?:3[Kk])?)? *[Ss]u\w* *#?\d{0,4}'

weapon:
  - '### (?:Affected DBID\(s\)|DBID to Copy)\n+(?:(?:[Cc][Ww])?[Dd][Bb](?:3[Kk])?)? *[Ww]e\w* *#?\d{0,4}'

sensor:
  - '### (?:Affected DBID\(s\)|DBID to Copy)\n+(?:(?:[Cc][Ww])?[Dd][Bb](?:3[Kk])?)? *[Ss]e\w* *#?\d{0,4}'

satellite:
  - '### (?:Affected DBID\(s\)|DBID to Copy)\n+(?:(?:[Cc][Ww])?[Dd][Bb](?:3[Kk])?)? *[Ss]a\w* *#?\d{0,4}'

loadout:
  - '### (?:Affected DBID\(s\)|DBID to Copy)\n+(?:(?:[Cc][Ww])?[Dd][Bb](?:3[Kk])?)? *[Ll]o\w* *#?\d{0,4}'

groundunit:
  - '### (?:Affected DBID\(s\)|DBID to Copy)\n+(?:(?:[Cc][Ww])?[Dd][Bb](?:3[Kk])?)? *[Gg]r\w* *#?\d{0,4}'

mount:
  - '### (?:Affected DBID\(s\)|DBID to Copy)\n+(?:(?:[Cc][Ww])?[Dd][Bb](?:3[Kk])?)? *[Mm]o\w* *#?\d{0,4}'
