# Add/remove 'DB3K' label if DB Selector is set to 'DB3K' or "Both".
DB3K:
  - '### DB Selector\n{1,}(DB3K|Both)'

# Add/remove 'CWDB' label if DB Selector is set to 'CWDB' or "Both".
CWDB:
  - '### DB Selector\n{1,}(CWDB|Both)'

# Add/remove 'hypo' label if Hypothetical selector is set to 'Yes'.
hypo:
  - '### Hypothetical\n{1,}Yes'