name: New Submarine Request
description: This form is used to request new submarines/USVs.
# title: "New Submarine: "
labels: ["addition", "submarine"]
# assignees:
#   - octocat

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to request a new sub.

        ### On Class Requests
        If you're requesting an entire class of sub rather than a specific vessel, please fill out the form as if for the class nameship. For example, if requesting the Virginia-class, fill out the form as if for SSN-774.

        If the class saw significant changes/blocks/flights/etc., it may be worth filing separate requests to cover these differences. Please fill out the follow-on forms as if for the block/flight nameship. For example, if requesting the Flight II Virginia-class, fill out the form as if for SSN-778.

  - type: dropdown
    attributes:
      label: DB Selector
      description: Is this for DB3K, CWDB, or both?
      multiple: false
      options:
        - DB3K
        - CWDB
        - Both
    validations:
      required: true

  - type: input
    attributes:
      label: Baseline
      description: |
        Is there is a sub in the DB you recommend we start from? This is different from a "Copy Entry" in that most of its values will be changed, but we can use this to estimate anything we aren't sure of.

        For example, a Type 035 is different enough from a Type 033 that we couldn't simply copy one to model the other -- but it'd be a fair starting point.
      placeholder: ex. 2530
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Basic Information

  - type: dropdown
    attributes:
      label: Hypothetical
      description: Is this a hypothetical vessel, i.e. one not yet or never placed in service?
      multiple: false
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: input
    attributes:
      label: Name
      description: Provide classification, pennant number, and name (where applicable).
      placeholder: ex. SS-161 Stingray
    validations:
      required: true

  - type: input
    attributes:
      label: Class
      placeholder: ex. Balao-class
    validations:
      required: false

  - type: input
    attributes:
      label: Country
      placeholder: ex. United States
    validations:
      required: false

  - type: input
    attributes:
      label: Service
      placeholder: ex. Navy
    validations:
      required: false

  - type: input
    attributes:
      label: In Commission
      description: |
        When was the *class* in service?
        
        If requesting a specific vessel, this will match the vessel's service dates. If requesting a class (and therefore modelling a nameship), the out-of-service date may be much later than the nameship's decommissioning.
      placeholder: ex. 1943-1971
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Dimensions and Tonnage

  - type: input
    attributes:
      label: Length (m)
      placeholder: ex. 95
    validations:
      required: true

  - type: input
    attributes:
      label: Beam (m)
      placeholder: ex. 8.3
    validations:
      required: true

  - type: input
    attributes:
      label: Draft (m)
      placeholder: ex. 5.1
    validations:
      required: true

  - type: input
    attributes:
      label: Standard Displacement (t)
      description: Interchangeable with normal. If only a single number is provided for displacement, assume it's standard.
      placeholder: ex. 1300
    validations:
      required: true

  - type: input
    attributes:
      label: Submerged Displacement (t)
      placeholder: ex. 1450
    validations:
      required: false

  - type: input
    attributes:
      label: Empty Displacement (t)
      placeholder: ex. 1000
    validations:
      required: false

  - type: input
    attributes:
      label: Max Depth (m)
      placeholder: ex. 350
    validations:
      required: false

  - type: input
    attributes:
      label: Complement
      placeholder: ex. 31
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Propulsion
        Please provide some information on propulsion, speeds, etc. for the sub.

  - type: dropdown
    attributes:
      label: Primary Propulsion Type
      multiple: false
      options:
        - Nuclear
        - Diesel/Electric
        - Diesel/Electric w/ AIP
        - Electric (UUVs)
    validations:
      required: true

  - type: input
    attributes:
      label: Propulsion
      description: Number, make, and type of primary engines. On diesel-electric subs, this will be the diesel engines.
      placeholder: ex. 4x Fairbanks-Morse Model 38D8 Diesels
    validations:
      required: true

  - type: input
    attributes:
      label: Flank Speed at Surface (kt)
      placeholder: ex. 20
    validations:
      required: true

  - type: input
    attributes:
      label: Flank Speed Submerged (kt)
      placeholder: ex. 24
    validations:
      required: false

  - type: input
    attributes:
      label: Range (nm) at Speed (kt)
      description: This will usually be at the sub's cruise speed.
      placeholder: ex. 1000nm @ 15kts
    validations:
      required: true

  - type: input
    attributes:
      label: Range (nm) on AIP
      description: If the sub is capable of AIP, how far is its range when using this method of propulsion?
      placeholder: ex. 850
    validations:
      required: false

  - type: input
    attributes:
      label: Fuel Capacity (kg)
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Sensing & Shooting

  - type: textarea
    attributes:
      label: Sensors
      description: | 
        List the sub's sensors, placing each on a new line as in the example.
      placeholder: |
        1x OMS 100 / SERO 400 Periscope Suite
        1x Type 1007 Radar
        1x DBQS-40 Sonar
    validations:
      required: true

  - type: textarea
    attributes:
      label: Mounts
      description: |
        List the sub's mounts (i.e., weapons), placing each on a new line as in the example. For torpedo tubes, VLS, etc. indicate what weapon(s) are loaded.
      placeholder: |
        6x 533mm TT (BSA Torpedoes)
        2x TAU-2000 DL
    validations:
      required: true

  - type: textarea
    attributes:
      label: Magazines
      description: |
        Describe the sub's available reloads, if known and applicable.
      placeholder: |
        6x BSA Torpedoes
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Miscellanious Capabilities

  - type: textarea
    attributes:
      label: Comms/Datalinks
      description: |
        List any known comms systems or datalinks, placing each mount on a new line as in the example.
      placeholder: |
        VHF/UHF Radio [Secure]
        SATCOM
        Link 11
        Link 14
        Link 16
    validations:
      required: false

  - type: dropdown
    attributes:
      label: sub Codes
      description: Indicate which (if any) of the following DB codes apply to this vessel.
      multiple: true
      options:
        - Shock Resistant
        - Nonmagnetic Hull
        - Titanium Hull
        - Double Hull
        - Shrouded Propulsor
        - Advanced Propulsor
        - Lithium-Ion Batteries
        - Snorkel
        - No Launch Transient
        - Low Construction Standards
        - Laid Down Before 1930
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Final Touches

  - type: textarea
    attributes:
      label: Comments
      description: Is there anything else you want to tell us so we can more effectively model this platform?
    validations:
      required: false

  - type: textarea
    attributes:
      label: Sources
      description: |
        Please list all the sources you used to find the information you provided. For offline sources, provide title, author, and page (as applicable).

        We do check these where possible. If we can't corroborate your information, we may provide replacements from our own sources or discard your request entirely.
    validations:
      required: true