name: New Satellite Request
description: This form is used to request a new satellite / satellite series.
# title: "New Satellite: "
labels: ["addition", "satellite"]
# assignees:
#   - octocat

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to request a new satellite.

  - type: dropdown
    attributes:
      label: DB Selector
      description: Is this for DB3K, CWDB, or both?
      multiple: false
      options:
        - DB3K
        - CWDB
        - Both
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Basic Information

  - type: dropdown
    attributes:
      label: Hypothetical
      description: Is this a hypothetical satellite, i.e. one not yet or never placed in service?
      multiple: false
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: input
    attributes:
      label: Series Name
      description: What is the satellite called? For satellite series, provide the general program name.
      placeholder: ex. Jumpseat
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Satellite Type
      description: Which best describes this satellite/series?
      multiple: false
      options:
        - IMGSAT
        - SIGINT
        - ELINT
        - MASINT
    validations:
      required: true

  - type: input
    attributes:
      label: Country
      placeholder: ex. United States
    validations:
      required: false

  - type: input
    attributes:
      label: Service
      placeholder: ex. Air Force
    validations:
      required: false

  - type: input
    attributes:
      label: In Commission
      description: When was this satellite/series in service?
      placeholder: ex. 1971-1985
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Dimensions and Weights
        These numbers are less important for satellites than, say, for aircraft, so don't worry if you can't find some (or any) of this data.

  - type: input
    attributes:
      label: Length (m)
      placeholder: ex. 1
    validations:
      required: false

  - type: input
    attributes:
      label: Width/Span (m)
      placeholder: ex. 1
    validations:
      required: false

  - type: input
    attributes:
      label: Height (m)
      placeholder: ex. 1
    validations:
      required: false

  - type: input
    attributes:
      label: Weight (kg)
      placeholder: ex. 100
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Orbital Data

  - type: dropdown
    attributes:
      label: Is Geostationary
      multiple: false
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: textarea
    attributes:
      label: COSPAR ID
      description: |
        Provide the COSPAR ID for each satellite in the series.
      placeholder: |
        USH-10: 2006-015B
    validations:
      required: true

  - type: textarea
    attributes:
      label: Launch/Comm. & Decom./Deorbit Date(s)
      description: |
        Provide the launch dates (+ commission date, if different) and decom./deorbit dates for each satellite in the series. This is different from the "In Commision" date provided earlier, which covers the entire series.
      placeholder: |
        NAG-15A: 24 DEC 84 // 28 APR 04 (Deorbit: 4 OCT 07)
    validations:
      required: true

  - type: textarea
    attributes:
      label: TLE
      description: |
        Provide a two or three line TLE for each satellite in the series.
      placeholder: |
        1 46320U 20061BA  21193.49823640  .00000228  00000-0  17253-4 0  9990
        2 46320  97.4876 266.6950 0001318 223.9323 261.1888 15.11370748 47168
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Sensor Package

  - type: textarea
    attributes:
      label: Sensors
      description: |
        List the satellite's sensors, placing each mount on a new line as in the example. Generic sensors are fine.
      placeholder: |
        1x Generic Satellite Visual Camera (3rd Gen)
        1x Generic Satellite SIGINT
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Final Touches

  - type: textarea
    attributes:
      label: Comments
      description: Is there anything else you want to tell us so we can more effectively model this platform?
    validations:
      required: false

  - type: textarea
    attributes:
      label: Sources
      description: |
        Please list all the sources you used to find the information you provided. For offline sources, provide title, author, and page (as applicable).

        We do check these. If we can't corroborate your information, we may provide replacement data from our own sources or discard your request entirely.
    validations:
      required: true