name: New Weapon Request
description: This form is used to request a new weapon.
# title: "New Weapon: "
labels: ["addition", "weapon"]
# assignees:
#   - octocat

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to request a new weapon.

        Please note that filing this form will ONLY result in the weapon itself being added, not necessarily any associated loadouts, mounts, etc. These should be requested separately.

        ### A Note on Requesting Subcomponents
        Subcomponents -- such as weapons and sensors -- are of little use without a host. While it is true that weapon records / sensors may be added to various platforms in the mission editor, a weapon/sensor that is not currently employed on any platform in the DB is rarely worth the time it takes to add.

        If the weapon/sensor *is* employed on another platform but not represented in the DB, it may be better to file an addition, update, or loadout request instead. If we need you to file a separate subcomponent request, we'll let you know.

  - type: dropdown
    attributes:
      label: DB Selector
      description: Is this for DB3K, CWDB, or both?
      multiple: false
      options:
        - DB3K
        - CWDB
        - Both
    validations:
      required: true

  - type: input
    attributes:
      label: Baseline
      description: |
        Is there is a weapon in the DB you recommend we start from? This is different from a "Copy Entry" in that most of its values will be changed, but we can use this to estimate anything we aren't sure of.

        For example, the AGM-88 is different enough from the older AGM-45 that we couldn't simply copy one to model the other -- but it'd be a fair starting point.
      placeholder: ex. 2530
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Common Information

  - type: dropdown
    attributes:
      label: Hypothetical
      description: Is this a hypothetical weapon, i.e. one not yet or never placed in service?
      multiple: false
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: input
    attributes:
      label: Name
      description: Provide designation and name (where applicable).
      placeholder: ex. MM.38 Exocet Blk 1
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Dimensions and Weights

  - type: input
    attributes:
      label: Length (m)
      placeholder: ex. 4.70
    validations:
      required: true

  - type: input
    attributes:
      label: Width/Span (m)
      placeholder: ex. 1.10
    validations:
      required: true

  - type: input
    attributes:
      label: Diameter (m)
      placeholder: ex. 0.35
    validations:
      required: true

  - type: input
    attributes:
      label: Weight (kg)
      placeholder: ex. 670
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Engagement Characteristics

  - type: input
    attributes:
      label: Range (nm)
      placeholder: ex. 2.0-23.0
    validations:
      required: true

  - type: input
    attributes:
      label: Target Altitude / Depth (ft)
      description: How deep/high can a target be and still be successfully engaged by this weapon? Specify AGL or ASL (or provide both).
      placeholder: ex. 200ft AGL - 35000ft ASL
    validations:
      required: false

  - type: input
    attributes:
      label: Target Speed (kts)
      description: How slow/fast can a target be and still be successfully engaged by this weapon?
      placeholder: ex. 50kts - 2000kts
    validations:
      required: false

  - type: input
    attributes:
      label: Launch Altitude / Depth (ft)
      description: How deep/high can a shooter be and still employ this weapon? Specify AGL or ASL (or provide both).
      placeholder: ex. 200ft AGL - 35000ft ASL
    validations:
      required: false

  - type: input
    attributes:
      label: LaunchSpeed (kts)
      description: How slow/fast can a shooter be and still employ this weapon?
      placeholder: ex. 270kts - 650kts
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Lethality

  - type: input
    attributes:
      label: Warhead
      description: What is the warhead weight and type?
      placeholder: ex. 165kg HE Blast/Frag
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Targets
      description: Indicate which of the following are valid targets for this weapon.
      multiple: true
      options:
        - Aircraft
        - Helicopter
        - Missile
        - Satellite
        - C-RAM (Counter Rocket, Artillery and Mortar)
        - Surface Vessel
        - Submarine
        - Mine
        - Torpedo
        - Land Structure - Soft
        - Land Structure - Hardened
        - Runway
        - Radar
        - Mobile Target - Soft
        - Mobile Target - Hardened
        - Mobile Target - Personnel
    validations:
      required: true

  - type: input
    attributes:
      label: CEP (m)
      description: What is the Circular Error Probable for the weapon against targets on land/surface?
      placeholder: ex. 4
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Sensors

  - type: textarea
    attributes:
      label: Sensors
      description: |
        List the weapon's sensors, placing each on a new line as in the example. Most weapons will have one or two for terminal guidance.

        If you have specific information about the seekers' capabilities, you can include it here.
      placeholder: |
        1x Active Radar Seeker (~5nm Range)
        1x IIR Seeker (2nd Gen)
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Capabilities

  - type: dropdown
    attributes:
      label: Weapon Codes
      description: Indicate which (if any) of the following DB codes apply to this weapon.
      multiple: true
      options:
        - Illuminate at Launch
        - Terminal Illumination
        - Supports Buddy Illumination
        - Home On Jam (HOJ)
        - Anti-Air Stern Chase
        - Anti-Air Rear-Aspect
        - Anti-Air All-Aspect
        - Anti-Air Dogfight (High Off-Boresight)
        - No Diving Target
        - Capable vs Seaskimmer
        - ARH AAW - No HQ Track Required
        - C-RAM Capable
        - Lock-On After Launch (LOAL) - CEC-Capable
        - Lock-On After Launch (LOAL)
        - Terrain Following
        - Launcher Occupied During Guidance
        - ARM Target Memory
        - Loiter Capability
        - Loiter Capability (Parachute)
        - Search Pattern
        - Drive-Through Logic
        - Bearing-Only Launch (BOL)
        - Ballistic Missile or Rocket Booster
        - Weapon - INS Navigation
        - Weapon - INS w/ GNSS Navigation
        - Weapon - TERCOM Navigation
        - Weapon - Pre-Briefed Target Only
        - Weapon - Can Target Specific Subsystems
        - Terminal Maneuver - Pop-up
        - Terminal Maneuver - Zig-Zag
        - Terminal Maneuver - Random (Advanced)
        - Re-Attack Capability
        - Weapon Altitude Control Possible
        - Attitude Control - Aerodynamic Only
        - Attitude Control - Non-Aerodynamic Only
        - Attitude Control - Combined
        - Uses GPS
        - Uses GLONASS
        - Uses BeiDou/COMPASS
        - Uses NavIC/IRNSS
        - Mine - Contact Fuze
        - Mine - Magnetic Fuze, Simple Magnetic
        - Mine - Magnetic Fuze, Total-Field Magnetometer
        - Mine - Passive Acoustic Fuze, Broad-Band (Simple)
        - Mine - Passive Acoustic Fuze, Narrow-Band (Advanced)
        - Mine - Pressure Fuze
        - Mine - Seismic Fuze
        - Mine - Delay Counter
        - Mine - Arming Delay
        - Mine - Target Discrimination / Identification
        - Mine - Remote Controlled
        - Is Retarded Munition
        - Torpedo - Straight-Running
        - Torpedo - Wake Homing (WH)
        - Torpedo - Straight-Running & Time Detonation
        - Torpedo - Pattern-Running
        - Level Cruise Flight
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Final Touches

  - type: textarea
    attributes:
      label: Comments
      description: Is there anything else you want to tell us so we can more effectively model this weapon?
    validations:
      required: false

  - type: textarea
    attributes:
      label: Sources
      description: |
        Please list all the sources you used to find the information you provided. For offline sources, provide title, author, and page (as applicable).

        We do check these. If we can't corroborate your information, we may provide replacement data from our own sources or discard your request entirely.
    validations:
      required: true