name: Bug Report
description: This form is for reporting bugs in the DB.
# title: "Bug Report: "
labels: ["update", "bug"]
# assignees:
#   - octocat

body:
  - type: markdown
    attributes:
      value: |
        Thank you for bringing our attention to a bug! This form is similar to the update request form, but will attract more attention from the devs.

        Only use this form for things which are actually *broken*: i.e., they don't work, or are so significantly screwed up that they make gameplay impossible. Inaccurate data alone only warrants a normal update request.

  - type: dropdown
    attributes:
      label: DB Selector
      description: Does this bug occur using DB3K or CWDB?
      multiple: false
      options:
        - DB3K
        - CWDB
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Report Details

  - type: input
    attributes:
      label: Affected DBID(s)
      description: Which DBIDs are affected by this bug? If the bug affects a wide array of units, a simple descriptor will suffice.
      placeholder: ex. 1305
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description of Problem
      description: What seems to be the problem?
      placeholder: |
        Plane has zero fuel.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Recommended Fix
      description: If it's obvious what needs to be done to fix the problem, let us know.
      placeholder: |
        Give it fuel.
    validations:
      required: false