name: New Aircraft Request
description: This form is used to request new aircraft.
# title: "New Aircraft: "
labels: ["addition", "aircraft"]
# assignees:
#   - octocat

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to request a new aircraft.

  - type: markdown
    attributes:
      value: |
        ## Basic Information

  - type: checkboxes
    attributes:
      label: Hypothetical
      description: Is this a hypothetical aircraft, i.e. one not yet or never placed in service?
      options:
        - label: "Yes"
          required: false

  - type: input
    attributes:
      label: Name
      description: Provide designation and name (where applicable).
      placeholder: ex. VF-1 Valkyrie
    validations:
      required: true

  - type: input
    attributes:
      label: Country
      placeholder: ex. United Nations
    validations:
      required: false

  - type: input
    attributes:
      label: Service
      placeholder: ex. Space Force
    validations:
      required: false

  - type: input
    attributes:
      label: In Commission
      description: When was this aircraft in service for the specified country?
      placeholder: ex. 2008-2013
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Dimensions and Weights

  - type: input
    attributes:
      label: Length (m)
      placeholder: ex. 14.2
    validations:
      required: true

  - type: input
    attributes:
      label: Wingspan (m)
      placeholder: ex. 14.8
    validations:
      required: true

  - type: input
    attributes:
      label: Height (m)
      placeholder: ex. 3.8
    validations:
      required: true

  - type: input
    attributes:
      label: Empty Weight (kg)
      placeholder: ex. 1400
    validations:
      required: true

  - type: input
    attributes:
      label: Maximum Takeoff Weight (MTOW) (kg)
      placeholder: ex. 1900
    validations:
      required: true

  - type: input
    attributes:
      label: Payload Weight (kg)
      placeholder: ex. 500
    validations:
      required: false

  - type: input
    attributes:
      label: Crew
      placeholder: ex. 2
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Propulsion

  - type: input
    attributes:
      label: Propulsion
      description: Number and make of engines.
      placeholder: ex. 2x P&W FF-2001
    validations:
      required: true

  - type: input
    attributes:
      label: Rate of Climb (ft/min)
      placeholder: ex. 800
    validations:
      required: false

  - type: input
    attributes:
      label: Service Ceiling (ft)
      placeholder: ex. 36000
    validations:
      required: true

  - type: input
    attributes:
      label: Military/Afterburner Speed (kt)
      placeholder: ex. 520
    validations:
      required: true

  - type: input
    attributes:
      label: Cruise Speed (kt)
      placeholder: ex. 480
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Supercruise
      description: Is this aircraft capable of supercruise?
      options:
        - label: "Yes"
          required: false

  - type: input
    attributes:
      label: Ferry Range (nm)
      description: Aircraft range at cruise speed w/ ferry loadout.
      placeholder: ex. 915
    validations:
      required: true

  - type: input
    attributes:
      label: Endurance (min)
      placeholder: ex. 600
    validations:
      required: false

  - type: input
    attributes:
      label: Takeoff / Landing Distance (m)
      placeholder: ex. 700 / 600
    validations:
      required: false

  - type: input
    attributes:
      label: Fuel Capacity (kg)
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Sensing & Shooting

  - type: textarea
    attributes:
      label: Sensors
      description: | 
        List the aircraft's sensors, placing each on a new line as in the example.
      placeholder: |
        1x AWG-20 FCR
        1x APS-21 Surveillance Radar
        2x Generic FLIR
        1x Generic EO/IR Ball
    validations:
      required: true

  - type: textarea
    attributes:
      label: Mounts
      description: |
        List the aircraft mounts (i.e., weapons), placing each on a new line as in the example. For aircraft, this will include only non-removable weapons, e.g. cannon; missiles, bombs, etc. should be listed as loadout options.
      placeholder: |
        1x ROV-20 Laser Cannon
        1x 55mm GU-11 Gun Pod (always installed)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Loadout Options
      description: |
        If specific loadouts are known, list them here. In addition / otherwise, please list the weapons that the aircraft can employ.
      placeholder: |
        - 12x AMM-1 Hybrid Guided Multipurpose Missiles
        - 12x Mk82 LDGB
        - 6x RMS-1 AShM
        - 4x UUM-7 Micro-Missile Pods (14x HMM-01/pod)

        Or combinations of the above.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Miscellanious Capabilities

  - type: textarea
    attributes:
      label: Comms/Datalinks
      description: |
        List any known comms systems or datalinks, placing each on a new line as in the example.
      placeholder: |
        UHF Radio [Secure]
        VHF Radio [Secure]
        UHF Datalink
    validations:
      required: false

  - type: dropdown
    attributes:
      label: Aircraft Codes
      description: Indicate which (if any) of the following DB codes apply to this aircraft.
      multiple: true
      options:
        - Supermanouverability
        - HIFR Capable
        - Terrain Avoidance
        - Terrain Following
        - Fly-by-Wire
        - Blip Enhance
        - Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles)
        - Night Navigation/Attack (Incl. Bomb, Rocket Delivery)
        - Bombsight - Basic
        - Bombsight - Ballistic Computing
        - Bombsight - Advanced Computing
        - Bombsight - Advanced Navigation (INS/GPS)
        - Helmet Mounted Sight / Display (HMS/HMD)
        - Probe Refuelling
        - Boom Refuelling
        - Centerline Drogue
        - Wing Drogue
        - Centerline Boom
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Final Touches

  - type: textarea
    attributes:
      label: Comments
      description: Is there anything else you want to tell us so we can more effectively model this platform?
    validations:
      required: false

  - type: textarea
    attributes:
      label: Sources
      description: |
        Please list all the sources you used to find the information you provided. For offline sources, provide title, author, and page (as applicable).

        We do check these. If we can't corroborate your information, we may provide replacement data from our own sources or discard your request entirely.
    validations:
      required: true