name: New Facility Request
description: This form is used to request new facilities (SAMs, SSMs, etc.).
# title: "New Facility: "
labels: ["addition", "facility"]
# assignees:
#   - octocat

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to request a new facility.

      # ### Facility or Ground Unit?
      # As a rule of thumb, if the system is defined by the effect it has *on other domains*, it's probably best modelled as a facility. A SAM system, for example, is meant to engage targets in the air; a coastal defense missile battery is intended to engage targets at sea; this despite both technically being land-based platforms.

      # Modelling as a Ground Unit is more appropriate for land combat vehicles, i.e. vehicles whose primary purpose is to spot, engage, and destroy other targets on land or otherwise influence operations in that domain. Tanks, APCs/IFVs, trucks, and cars are all examples of vehicles best modelled in the Ground Units annex.

  - type: dropdown
    attributes:
      label: DB Selector
      description: Is this for DB3K or CWDB?
      multiple: false
      options:
        - DB3K
        - CWDB
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Basic Information

  - type: checkboxes
    attributes:
      label: Hypothetical
      description: Is this a hypothetical facility, i.e. one not yet or never placed in service?
      options:
        - label: "Yes"
          required: false

  - type: input
    attributes:
      label: Name
      description: Provide a name for the facility.
      placeholder: ex. SSM Btn (SM-62A Snark)
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Facility Type
      description: Choose the type descriptor that best describes this facility. In most cases this will match the name.
      multiple: false
      options:
        - Radar
        - SAM
        - AAA
        - Arty
        - SSM
        - Armored
        - Inf
        - Mech
        - Motor
        - Ammo
        - Fuel
        - Supply
    validations:
      required: true 

  - type: input
    attributes:
      label: Country
      placeholder: ex. United States
    validations:
      required: false

  - type: input
    attributes:
      label: Service
      placeholder: ex. Army
    validations:
      required: false

  - type: input
    attributes:
      label: In Commission
      description: When was the facility in service?
      placeholder: ex. 1959-1961
    validations:
      required: false

  - type: input
    attributes:
      label: Crew
      placeholder: ex. 40
    validations:
      required: false

  - type: input
    attributes:
      label: Dispersion Radius (m)
      description: How far apart are the individual "mounts" usually positioned? For example, in a SAM site, how far apart are the TELs?
      placeholder: ex. 40
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Sensing & Shooting

  - type: textarea
    attributes:
      label: Sensors
      description: |
        List the facility's sensors where applicable, placing each on a new line as in the example.
      placeholder: |
        1x KALKAN-II Radar
        1x ASELFLIR-300D EOS
    validations:
      required: true

  - type: textarea
    attributes:
      label: Mounts
      description: |
        List the facility's mounts (i.e., weapons) where applicable, placing each on a new line.
      placeholder: |
        3x HISAR-A TEL
    validations:
      required: true

  - type: textarea
    attributes:
      label: Magazines
      description: |
        List the facility's available reloads.
      placeholder: |
        24x HISAR-A Missles
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Miscellanious Capabilities

  - type: textarea
    attributes:
      label: Aircraft & Docking Facilities
      description: List any docking and/or aircraft facilities, placing each on a new line.
      placeholder: |
        1x Pad (Medium Aircraft)
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Final Touches

  - type: textarea
    attributes:
      label: Comments
      description: Is there anything else you want to tell us so we can more effectively model this platform?
    validations:
      required: false

  - type: textarea
    attributes:
      label: Sources
      description: |
        Please list all the sources you used to find the information you provided. For offline sources, provide title, author, and page (as applicable).

        We do check these. If we can't corroborate your information, we may provide replacement data from our own sources or discard your request entirely.
    validations:
      required: true